name: CI
on:
  pull_request:
    paths-ignore:
    - README.md
  push:
    branches:
    - main

jobs:
  core-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Docker image
      working-directory: .
      run: docker build -t pirkka-price -f ./Dockerfile .

  core:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - uses: actions/checkout@v1

    - name: Conventional Commits
      uses: webiny/action-conventional-commits@v1.1.0

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Typecheck
      working-directory: ./apps/core
      run: npm run typescript-check
    
    - name: Lint
      working-directory: ./apps/core
      run: npm run lint
